# Generated by Django 5.0.2 on 2024-03-20 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_auctionlisting_bid_auctionlisting_highest_bid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="highest_bid",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auctions.bid",
            ),
        ),
    ]
