# Generated by Django 5.0.2 on 2024-03-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_alter_auctionlisting_highest_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="current_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="starting_price",
            field=models.FloatField(),
        ),
    ]
