# Generated by Django 5.0.2 on 2024-03-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_alter_auctionlisting_bidding_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="img",
            field=models.URLField(blank=True, null=True),
        ),
    ]
