# Generated by Django 5.0.2 on 2024-03-21 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_auctionlisting_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionlisting",
            old_name="img",
            new_name="image",
        ),
    ]
