# Generated by Django 5.0.2 on 2024-03-22 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0011_auctionlisting_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="watch_list",
            new_name="watchlist",
        ),
    ]
