# Generated by Django 5.0.2 on 2024-03-27 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0013_remove_auctionlisting_highest_bid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionlisting",
            old_name="time",
            new_name="created_at",
        ),
    ]
