# Generated by Django 5.0.2 on 2024-03-27 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0014_rename_time_auctionlisting_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="bidder",
            new_name="commenter",
        ),
    ]
