# Generated by Django 5.0.2 on 2024-03-31 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0015_rename_bidder_comment_commenter"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="highest_bid",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highest_bid",
                to="auctions.bid",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="watchlist_user",
                to="auctions.auctionlisting",
            ),
        ),
    ]
