# Generated by Django 5.0.2 on 2024-03-31 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0016_auctionlisting_highest_bid_alter_user_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="highest_bid",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highest_bid",
                to="auctions.bid",
            ),
        ),
    ]
